### ISSUE TITLE
relative path entries and the location of the database file

### ISSUE THREAD

**Issue by smallsaucepan** [degami/ProjectPHPClassBrowser#3]
Hello degami.

I was having some issues getting your plugin to work. I've figured out what was going on and thought you might like to know the cause. I'm using ST3 on mac.

The problem occurs when the directories in the project are sub directories of the folder holding the sublime-project file. When this happens ST3 stores path values as relative directories, rather than absolute.

For example, my project file is ~home/my.sublime-project and contains two directories ~home/www/some/stuff/ and ~/home/www/other/things/

Below is the resulting my.sublime-project

    {
        "folders":
        [
            {
                "path": "www/src/some/stuff"
            },
            {
                "path": "www/src/other/things"
            }
        ]
    }

The error I get when rebuilding the database is:

    No such file or directory: www/src/some/stuff/phpclass.sublime-classdb

As a workaround, if I save my sublime-project file to ~home/blah/ ST3 uses absolute path values, and the plugin works as expected.

Not sure how you'd want to do it, but perhaps if the path appears to be relative, prepend the directory location of the sublime-project file? Or maybe store the database in the same directory as the sublime-project file to avoid placing it in the first project path?

Cheers
James

**Comment by degami** [comment]
Hi James,
thanks for your issue (and for the well done description and suggestion too). I've tried to fix it, prepending the project file's directory path in case the "folders" in the project do not start with / (a slash)

i hope it will work. Let me know.

thanks again
Mirko
